const MHCities = [
  {label: 'Achalpur', value: 'Achalpur'},
  {label: 'Ahmadpur', value: 'Ahmadpur'},
  {label: 'Airoli', value: 'Airoli'},
  {label: 'Ajara', value: 'Ajara'},
  {label: 'Akalkot', value: 'Akalkot'},
  {label: 'Akola', value: 'Akola'},
  {label: 'Akot', value: 'Akot'},
  {label: 'Alandi', value: 'Alandi'},
  {label: 'Allapalli', value: 'Allapalli'},
  {label: 'Alibag', value: 'Alibag'},
  {label: 'Amalner', value: 'Amalner'},
  {label: 'Amarnath', value: 'Amarnath'},
  {label: 'Ambad', value: 'Ambad'},
  {label: 'Ambajogai', value: 'Ambajogai'},
  {label: 'Amravati', value: 'Amravati'},
  {label: 'Anjangaon', value: 'Anjangaon'},
  {label: 'Anshing', value: 'Anshing'},
  {label: 'Artist Village', value: 'Artist Village'},
  {label: 'Ashta', value: 'Ashta'},
  {label: 'Ashti', value: 'Ashti'},
  {label: 'Aurangabad', value: 'Aurangabad'},
  {label: 'Ausa', value: 'Ausa'},
  {label: 'Badlapur', value: 'Badlapur'},
  {label: 'Ballalpur', value: 'Ballalpur'},
  {label: 'Basmat', value: 'Basmat'},
  {label: 'Beed', value: 'Beed'},
  {label: 'Bhandara', value: 'Bhandara'},
  {label: 'Bhayandar', value: 'Bhayandar'},
  {label: 'Bhigvan', value: 'Bhigvan'},
  {label: 'Bhiwandi', value: 'Bhiwandi'},
  {label: 'Bhor', value: 'Bhor'},
  {label: 'Bhudgaon', value: 'Bhudgaon'},
  {label: 'Bhusaval', value: 'Bhusaval'},
  {label: 'Bhoom', value: 'Bhoom'},
  {label: 'Beed', value: 'Beed'},
  {label: 'Biloli', value: 'Biloli'},
  {label: 'Boisar', value: 'Boisar'},
  {label: 'Buldana', value: 'Buldana'},
  {label: 'Balapur', value: 'Balapur'},
  {label: 'Barsi', value: 'Barsi'},
  {label: 'Baramati', value: 'Baramati'},
  {label: 'Chandrapur', value: 'Chandrapur'},
  {label: 'Chicholi', value: 'Chicholi'},
  {label: 'Chikhli (Buldhana)', value: 'Chikhli (Buldhana)'},
  {label: 'Chinchani', value: 'Chinchani'},
  {label: 'Chiplun', value: 'Chiplun'},
  {label: 'Chopda', value: 'Chopda'},
  {label: 'Chakan', value: 'Chakan'},
  {label: 'Chalisgaon', value: 'Chalisgaon'},
  {label: 'Chanda', value: 'Chanda'},
  {label: 'Chandor', value: 'Chandor'},
  {label: 'Chandur', value: 'Chandur'},
  {label: 'Chandur Bazar', value: 'Chandur Bazar'},
  {label: 'Daryapur', value: 'Daryapur'},
  {label: 'Dattapur', value: 'Dattapur'},
  {label: 'Daulatabad', value: 'Daulatabad'},
  {label: 'Daund', value: 'Daund'},
  {label: 'Dehu', value: 'Dehu'},
  {label: 'Deoli', value: 'Deoli'},
  {label: 'Deolali', value: 'Deolali'},
  {label: 'Deulgaon Raja', value: 'Deulgaon Raja'},
  {label: 'Dharangaon', value: 'Dharangaon'},
  {label: 'Dharmabad', value: 'Dharmabad'},
  {label: 'Dhule', value: 'Dhule'},
  {label: 'Dharur', value: 'Dharur'},
  {label: 'Dhulia', value: 'Dhulia'},
  {label: 'Digras', value: 'Digras'},
  {label: 'Dombivli', value: 'Dombivli'},
  {label: 'Dondaicha', value: 'Dondaicha'},
  {label: 'Dudhani', value: 'Dudhani'},
  {label: 'Durgapur', value: 'Durgapur'},
  {label: 'Dabhol', value: 'Dabhol'},
  {label: 'Dahanu', value: 'Dahanu'},
  {label: 'Darwha', value: 'Darwha'},
  {label: 'Diglur', value: 'Diglur'},
  {label: 'Erandol', value: 'Erandol'},
  {label: 'Faizpur', value: 'Faizpur'},
  {label: 'Gadchiroli', value: 'Gadchiroli'},
  {label: 'Gadhinglaj', value: 'Gadhinglaj'},
  {label: 'Gangakher', value: 'Gangakher'},
  {label: 'Gangapur', value: 'Gangapur'},
  {label: 'Gevrai', value: 'Gevrai'},
  {label: 'Ghoti Budrukh', value: 'Ghoti Budrukh'},
  {label: 'Ghugus', value: 'Ghugus'},
  {label: 'Ghatanji', value: 'Ghatanji'},
  {label: 'Goregaon', value: 'Goregaon'},
  {label: 'Guhagar', value: 'Guhagar'},
  {label: 'Hadgaon', value: 'Hadgaon'},
  {label: 'Harnai', value: 'Harnai'},
  {label: 'Hinganghat', value: 'Hinganghat'},
  {label: 'Hingoli', value: 'Hingoli'},
  {label: 'Hirapur Hamesha', value: 'Hirapur Hamesha'},
  {label: 'Ichalkaranji', value: 'Ichalkaranji'},
  {label: 'Igatpuri', value: 'Igatpuri'},
  {label: 'Indapur', value: 'Indapur'},
  {label: 'Jaisingpur', value: 'Jaisingpur'},
  {label: 'Jalgaon', value: 'Jalgaon'},
  {label: 'Jalgaon Jamod', value: 'Jalgaon Jamod'},
  {label: 'Jalna', value: 'Jalna'},
  {label: 'Jawhar', value: 'Jawhar'},
  {label: 'Jejuri', value: 'Jejuri'},
  {label: 'Jintur', value: 'Jintur'},
  {label: 'Junnar', value: 'Junnar'},
  {label: 'Kalamb', value: 'Kalamb'},
  {label: 'Kalamnuri', value: 'Kalamnuri'},
  {label: 'Kalas', value: 'Kalas'},
  {label: 'Kalmeshwar', value: 'Kalmeshwar'},
  {label: 'Kalyan', value: 'Kalyan'},
  {label: 'Kankauli', value: 'Kankauli'},
  {label: 'Kannad', value: 'Kannad'},
  {label: 'Karjat', value: 'Karjat'},
  {label: 'Karmala', value: 'Karmala'},
  {label: 'Karad', value: 'Karad'},
  {label: 'Khadki', value: 'Khadki'},
  {label: 'Kharakvasla', value: 'Kharakvasla'},
  {label: 'Khed', value: 'Khed'},
  {label: 'Khetia', value: 'Khetia'},
  {label: 'Khopoli', value: 'Khopoli'},
  {label: 'Khuldabad', value: 'Khuldabad'},
  {label: 'Khamgaon', value: 'Khamgaon'},
  {label: 'Khapa', value: 'Khapa'},
  {label: 'Kinwat', value: 'Kinwat'},
  {label: 'Kodoli', value: 'Kodoli'},
  {label: 'Kolhapur', value: 'Kolhapur'},
  {label: 'Kondalwadi', value: 'Kondalwadi'},
  {label: 'Kopargaon', value: 'Kopargaon'},
  {label: 'Koregaon', value: 'Koregaon'},
  {label: 'Koradi', value: 'Koradi'},
  {label: 'Koynanagar', value: 'Koynanagar'},
  {label: 'Kudal', value: 'Kudal'},
  {label: 'Kurandvad', value: 'Kurandvad'},
  {label: 'Kurduvadi', value: 'Kurduvadi'},
  {label: 'Kagal', value: 'Kagal'},
  {label: 'Kalundri', value: 'Kalundri'},
  {label: 'Kandri', value: 'Kandri'},
  {label: 'Karanja', value: 'Karanja'},
  {label: 'Kati', value: 'Kati'},
  {label: 'Katol', value: 'Katol'},
  {label: 'Latur', value: 'Latur'},
  {label: 'Lohogaon', value: 'Lohogaon'},
  {label: 'Lonavla', value: 'Lonavla'},
  {label: 'Lonar', value: 'Lonar'},
  {label: 'Lanja', value: 'Lanja'},
  {label: 'Lasalgaon', value: 'Lasalgaon'},
  {label: 'Mahabaleshwar', value: 'Mahabaleshwar'},
  {label: 'Mahad', value: 'Mahad'},
  {label: 'Maindargi', value: 'Maindargi'},
  {label: 'Malkapur', value: 'Malkapur'},
  {label: 'Manchar', value: 'Manchar'},
  {label: 'Mangrul Pir', value: 'Mangrul Pir'},
  {label: 'Manmad', value: 'Manmad'},
  {label: 'Manor', value: 'Manor'},
  {label: 'Mansar', value: 'Mansar'},
  {label: 'Mehekar', value: 'Mehekar'},
  {label: 'Mhasla', value: 'Mhasla'},
  {label: 'Mhasvad', value: 'Mhasvad'},
  {label: 'Mohpa', value: 'Mohpa'},
  {label: 'Moram', value: 'Moram'},
  {label: 'Morsi', value: 'Morsi'},
  {label: 'Mowad', value: 'Mowad'},
  {label: 'Mudkhed', value: 'Mudkhed'},
  {label: 'Mukher', value: 'Mukher'},
  {label: 'Mumbai', value: 'Mumbai'},
  {label: 'Mumbai Suburban', value: 'Mumbai Suburban'},
  {label: 'Murbad', value: 'Murbad'},
  {label: 'Murgud', value: 'Murgud'},
  {label: 'Murtajapur', value: 'Murtajapur'},
  {label: 'Murud (Raigad)', value: 'Murud (Raigad)'},
  {label: 'Majalgaon', value: 'Majalgaon'},
  {label: 'Makhjan', value: 'Makhjan'},
  {label: 'Malegaon', value: 'Malegaon'},
  {label: 'Malvan', value: 'Malvan'},
  {label: 'Manwat', value: 'Manwat'},
  {label: 'Matheran', value: 'Matheran'},
  {label: 'Mul', value: 'Mul'},
  {label: 'Nagpur', value: 'Nagpur'},
  {label: 'Nagpur Division', value: 'Nagpur Division'},
  {label: 'Naldurg', value: 'Naldurg'},
  {label: 'Nanded', value: 'Nanded'},
  {label: 'Nandurbar', value: 'Nandurbar'},
  {label: 'Nashik', value: 'Nashik'},
  {label: 'Nashik Division', value: 'Nashik Division'},
  {label: 'Navi Mumbai', value: 'Navi Mumbai'},
  {label: 'Neral', value: 'Neral'},
  {label: 'Nilanga', value: 'Nilanga'},
  {label: 'Nipani', value: 'Nipani'},
  {label: 'Nagothana', value: 'Nagothana'},
  {label: 'Nandgaon', value: 'Nandgaon'},
  {label: 'Nandura Buzurg', value: 'Nandura Buzurg'},
  {label: 'Osmanabad', value: 'Osmanabad'},
  {label: 'Ozar', value: 'Ozar'},
  {label: 'Paithan', value: 'Paithan'},
  {label: 'Pandharpur', value: 'Pandharpur'},
  {label: 'Panhala', value: 'Panhala'},
  {label: 'Panvel', value: 'Panvel'},
  {label: 'Parbhani', value: 'Parbhani'},
  {label: 'Parli Vaijnath', value: 'Parli Vaijnath'},
  {label: 'Parola', value: 'Parola'},
  {label: 'Partur', value: 'Partur'},
  {label: 'Pawni', value: 'Pawni'},
  {label: 'Pen', value: 'Pen'},
  {label: 'Phaltan', value: 'Phaltan'},
  {label: 'Pimpri', value: 'Pimpri'},
  {label: 'Powai', value: 'Powai'},
  {label: 'Pulgaon', value: 'Pulgaon'},
  {label: 'Pune', value: 'Pune'},
  {label: 'Pune Division', value: 'Pune Division'},
  {label: 'Pusad', value: 'Pusad'},
  {label: 'Pachora', value: 'Pachora'},
  {label: 'Palghar', value: 'Palghar'},
  {label: 'Panchgani', value: 'Panchgani'},
  {label: 'Patan', value: 'Patan'},
  {label: 'Pathardi', value: 'Pathardi'},
  {label: 'Pathri', value: 'Pathri'},
  {label: 'Patur', value: 'Patur'},
  {label: 'Pipri', value: 'Pipri'},
  {label: 'Purna', value: 'Purna'},
  {label: 'Rahimatpur', value: 'Rahimatpur'},
  {label: 'Raigarh', value: 'Raigarh'},
  {label: 'Ratnagiri', value: 'Ratnagiri'},
  {label: 'Revadanda', value: 'Revadanda'},
  {label: 'Risod', value: 'Risod'},
  {label: 'Roha', value: 'Roha'},
  {label: 'Rahuri', value: 'Rahuri'},
  {label: 'Rajgurunagar', value: 'Rajgurunagar'},
  {label: 'Rajur', value: 'Rajur'},
  {label: 'Rajapur', value: 'Rajapur'},
  {label: 'Rajura', value: 'Rajura'},
  {label: 'Ramtek', value: 'Ramtek'},
  {label: 'Raver', value: 'Raver'},
  {label: 'Sangamner', value: 'Sangamner'},
  {label: 'Sangli', value: 'Sangli'},
  {label: 'Saoner', value: 'Saoner'},
  {label: 'Satara', value: 'Satara'},
  {label: 'Satara Division', value: 'Satara Division'},
  {label: 'Satana', value: 'Satana'},
  {label: 'Selu', value: 'Selu'},
  {label: 'Shegaon', value: 'Shegaon'},
  {label: 'Shiraguppi', value: 'Shiraguppi'},
  {label: 'Shirdi', value: 'Shirdi'},
  {label: 'Shirgaon', value: 'Shirgaon'},
  {label: 'Shirpur', value: 'Shirpur'},
  {label: 'Shirwal', value: 'Shirwal'},
  {label: 'Shivaji Nagar', value: 'Shivaji Nagar'},
  {label: 'Shrigonda', value: 'Shrigonda'},
  {label: 'Shahada', value: 'Shahada'},
  {label: 'Shahapur', value: 'Shahapur'},
  {label: 'Sillod', value: 'Sillod'},
  {label: 'Sindhudurg', value: 'Sindhudurg'},
  {label: 'Sindi', value: 'Sindi'},
  {label: 'Sinnar', value: 'Sinnar'},
  {label: 'Sirur', value: 'Sirur'},
  {label: 'Solapur', value: 'Solapur'},
  {label: 'Sonegaon', value: 'Sonegaon'},
  {label: 'Soygaon', value: 'Soygaon'},
  {label: 'Srivardhan', value: 'Srivardhan'},
  {label: 'Surgana', value: 'Surgana'},
  {label: 'Sangola', value: 'Sangola'},
  {label: 'Savantvadi', value: 'Savantvadi'},
  {label: 'Savda', value: 'Savda'},
  {label: 'Talegaon Dabhade', value: 'Talegaon Dabhade'},
  {label: 'Taloda', value: 'Taloda'},
  {label: 'Telhara', value: 'Telhara'},
  {label: 'Thane', value: 'Thane'},
  {label: 'Trimbak', value: 'Trimbak'},
  {label: 'Tuljapur', value: 'Tuljapur'},
  {label: 'Tumsar', value: 'Tumsar'},
  {label: 'Tarapur', value: 'Tarapur'},
  {label: 'Tasgaon', value: 'Tasgaon'},
  {label: 'Udgir', value: 'Udgir'},
  {label: 'Ulhasnagar', value: 'Ulhasnagar'},
  {label: 'Umarga', value: 'Umarga'},
  {label: 'Umarkhed', value: 'Umarkhed'},
  {label: 'Umred', value: 'Umred'},
  {label: 'Uran', value: 'Uran'},
  {label: 'Vaijapur', value: 'Vaijapur'},
  {label: 'Varangaon', value: 'Varangaon'},
  {label: 'Vasind', value: 'Vasind'},
  {label: 'Vengurla', value: 'Vengurla'},
  {label: 'Virar', value: 'Virar'},
  {label: 'Vite', value: 'Vite'},
  {label: 'Vada', value: 'Vada'},
  {label: 'Wadgaon', value: 'Wadgaon'},
  {label: 'Wai', value: 'Wai'},
  {label: 'Wani', value: 'Wani'},
  {label: 'Wardha', value: 'Wardha'},
  {label: 'Warora', value: 'Warora'},
  {label: 'Warud', value: 'Warud'},
  {label: 'Washim', value: 'Washim'},
  {label: 'Yavatmal', value: 'Yavatmal'},
  {label: 'Yeola', value: 'Yeola'},
  {label: 'Yaval', value: 'Yaval'},
  {label: 'Arangaon', value: 'Arangaon'},
  {label: 'Arvi', value: 'Arvi'},
  {label: 'Adawad', value: 'Adawad'},
  {label: 'Agar Panchaitan', value: 'Agar Panchaitan'},
  {label: 'Aheri', value: 'Aheri'},
  {label: 'Ahmednagar', value: 'Ahmednagar'},
  {label: 'Akluj', value: 'Akluj'},
  {label: 'Akolner', value: 'Akolner'},
  {label: 'Akrani', value: 'Akrani'},
  {label: 'Ale', value: 'Ale'},
  {label: 'Alkuti', value: 'Alkuti'},
  {label: 'Ambernath', value: 'Ambernath'},
  {label: 'Ambegaon', value: 'Ambegaon'},
  {label: 'Amgaon', value: 'Amgaon'},
  {label: 'Andheri', value: 'Andheri'},
  {label: 'Andura', value: 'Andura'},
  {label: 'Anjarle', value: 'Anjarle'},
  {label: 'Arag', value: 'Arag'},
  {label: 'Ardhapur', value: 'Ardhapur'},
  {label: 'Argaon', value: 'Argaon'},
  {label: 'Asoda', value: 'Asoda'},
  {label: 'Assaye', value: 'Assaye'},
  {label: 'Astagaon', value: 'Astagaon'},
  {label: 'Aundh Satara', value: 'Aundh Satara'},
  {label: 'Badnapur', value: 'Badnapur'},
  {label: 'Badnera', value: 'Badnera'},
  {label: 'Bagewadi', value: 'Bagewadi'},
  {label: 'Balapur Akola district', value: 'Balapur Akola district'},
  {label: 'Ballard Estate', value: 'Ballard Estate'},
  {label: 'Ballarpur', value: 'Ballarpur'},
  {label: 'Banda Maharashtra', value: 'Banda Maharashtra'},
  {label: 'Bandra', value: 'Bandra'},
  {label: 'Baner', value: 'Baner'},
  {label: 'Bankot', value: 'Bankot'},
  {label: 'Bavdhan', value: 'Bavdhan'},
  {label: 'Bawanbir', value: 'Bawanbir'},
  {label: 'Bhadgaon Maharashtra', value: 'Bhadgaon Maharashtra'},
  {label: 'Bhandardara', value: 'Bhandardara'},
  {label: 'Bhandup', value: 'Bhandup'},
  {label: 'Bhiwapur', value: 'Bhiwapur'},
  {label: 'Bhokar', value: 'Bhokar'},
  {label: 'Bhokardan', value: 'Bhokardan'},
  {label: 'Bhoom', value: 'Bhoom'},
  {label: 'Bhugaon', value: 'Bhugaon'},
  {label: 'Bijur', value: 'Bijur'},
  {label: 'Bilashi', value: 'Bilashi'},
  {label: 'Borgaon Manju', value: 'Borgaon Manju'},
  {label: 'Borivali', value: 'Borivali'},
  {label: 'Brahmapuri', value: 'Brahmapuri'},
  {label: 'Breach Candy', value: 'Breach Candy'},
  {label: 'Byculla', value: 'Byculla'},
  {label: 'Chakur', value: 'Chakur'},
  {label: 'Chandgad', value: 'Chandgad'},
  {label: 'Chausala', value: 'Chausala'},
  {label: 'Chembur', value: 'Chembur'},
  {label: 'Chichondi Patil', value: 'Chichondi Patil'},
  {label: 'Chikhli (Jalna)', value: 'Chikhli (Jalna)'},
  {label: 'Chimur', value: 'Chimur'},
  {label: 'Chinchpokli', value: 'Chinchpokli'},
  {label: 'Colaba', value: 'Colaba'},
  {label: 'Daddi', value: 'Daddi'},
  {label: 'Dahivel', value: 'Dahivel'},
  {label: 'Dapoli', value: 'Dapoli'},
  {label: 'Deccan Gymkhana', value: 'Deccan Gymkhana'},
  {label: 'Deglur', value: 'Deglur'},
  {label: 'Deolapar', value: 'Deolapar'},
  {label: 'Deoni', value: 'Deoni'},
  {label: 'Devrukh', value: 'Devrukh'},
  {label: 'Dharavi', value: 'Dharavi'},
  {label: 'Dhawalpuri', value: 'Dhawalpuri'},
  {label: 'Dighori', value: 'Dighori'},
  {label: 'Dindori Maharashtra', value: 'Dindori Maharashtra'},
  {label: 'Diveagar', value: 'Diveagar'},
  {label: 'Dongri', value: 'Dongri'},
  {label: 'Durgapur Chandrapur', value: 'Durgapur Chandrapur'},
  {label: 'Fort', value: 'Fort'},
  {label: 'Ganpatipule', value: 'Ganpatipule'},
  {label: 'Ghargaon', value: 'Ghargaon'},
  {label: 'Ghatkopar', value: 'Ghatkopar'},
  {label: 'Girgaon', value: 'Girgaon'},
  {label: 'Gondia', value: 'Gondia'},
  {label: 'Gorai', value: 'Gorai'},
  {label: 'Hadapsar Pune', value: 'Hadapsar Pune'},
  {label: 'Halkarni', value: 'Halkarni'},
  {label: 'Harangul', value: 'Harangul'},
  {label: 'Helwak', value: 'Helwak'},
  {label: 'Hirapur', value: 'Hirapur'},
  {label: 'Hotgi', value: 'Hotgi'},
  {label: 'Jaitapur', value: 'Jaitapur'},
  {label: 'Jakhangaon', value: 'Jakhangaon'},
  {label: 'Jalkot', value: 'Jalkot'},
  {label: 'Jamkhed', value: 'Jamkhed'},
  {label: 'Jamod', value: 'Jamod'},
  {label: 'Janephal', value: 'Janephal'},
  {label: 'Jaoli', value: 'Jaoli'},
  {label: 'Jat Sangli', value: 'Jat Sangli'},
  {label: 'Jategaon', value: 'Jategaon'},
  {label: 'Jaysingpur', value: 'Jaysingpur'},
  {label: 'Jogeshwari', value: 'Jogeshwari'},
  {label: 'Juhu', value: 'Juhu'},
  {label: 'Kachurwahi', value: 'Kachurwahi'},
  {label: 'Kadegaon', value: 'Kadegaon'},
  {label: 'Kadus', value: 'Kadus'},
  {label: 'Kaij', value: 'Kaij'},
  {label: 'Kalamb Osmanabad', value: 'Kalamb Osmanabad'},
  {label: 'Kalamboli', value: 'Kalamboli'},
  {label: 'Kali(DK)', value: 'Kali(DK)'},
  {label: 'Kalyani Nagar', value: 'Kalyani Nagar'},
  {label: 'Kamargaon', value: 'Kamargaon'},
  {label: 'Kamatgi', value: 'Kamatgi'},
  {label: 'Kamptee', value: 'Kamptee'},
  {label: 'Kankavli', value: 'Kankavli'},
  {label: 'Karajagi', value: 'Karajagi'},
  {label: 'Karanja Lad', value: 'Karanja Lad'},
  {label: 'Karkamb', value: 'Karkamb'},
  {label: 'Kasara', value: 'Kasara'},
  {label: 'Kasoda', value: 'Kasoda'},
  {label: 'Katral', value: 'Katral'},
  {label: 'Khalapur', value: 'Khalapur'},
  {label: 'Khallar', value: 'Khallar'},
  {label: 'Khanapur', value: 'Khanapur'},
  {label: 'Khandala', value: 'Khandala'},
  {label: 'Khangaon', value: 'Khangaon'},
  {label: 'Kharda', value: 'Kharda'},
  {label: 'Kharghar', value: 'Kharghar'},
  {label: 'Kharsundi', value: 'Kharsundi'},
  {label: 'Khoni', value: 'Khoni'},
  {label: 'Kondhali', value: 'Kondhali'},
  {label: 'Kopar Khairane', value: 'Kopar Khairane'},
  {label: 'Kopela', value: 'Kopela'},
  {label: 'Kuhi', value: 'Kuhi'},
  {label: 'Kurankhed', value: 'Kurankhed'},
  {label: 'Kusumba', value: 'Kusumba'},
  {label: 'Lakhandur', value: 'Lakhandur'},
  {label: 'Lavasa', value: 'Lavasa'},
  {label: 'Mahape', value: 'Mahape'},
  {label: 'Mahim', value: 'Mahim'},
  {label: 'Malabar Hill', value: 'Malabar Hill'},
  {label: 'Malad', value: 'Malad'},
  {label: 'Mandangad', value: 'Mandangad'},
  {label: 'Mandhal', value: 'Mandhal'},
  {label: 'Mandwa', value: 'Mandwa'},
  {label: 'Mangaon', value: 'Mangaon'},
  {label: 'Manjlegaon', value: 'Manjlegaon'},
  {label: 'Mankeshwar', value: 'Mankeshwar'},
  {label: 'Mankhurd', value: 'Mankhurd'},
  {label: 'Maregaon', value: 'Maregaon'},
  {label: 'Mastiholi', value: 'Mastiholi'},
  {label: 'Masur India', value: 'Masur India'},
  {label: 'Matunga', value: 'Matunga'},
  {label: 'Mazagaon', value: 'Mazagaon'},
  {label: 'Mehergaon', value: 'Mehergaon'},
  {label: 'Mehkar', value: 'Mehkar'},
  {label: 'Miraj', value: 'Miraj'},
  {label: 'Mohadi', value: 'Mohadi'},
  {label: 'Mohol', value: 'Mohol'},
  {label: 'Mokhada taluka', value: 'Mokhada taluka'},
  {label: 'Mora Maharashtra', value: 'Mora Maharashtra'},
  {label: 'Mulher', value: 'Mulher'},
  {label: 'Mulund', value: 'Mulund'},
  {label: 'Murud (Ratnagiri)', value: 'Murud (Ratnagiri)'},
  {label: 'Murum', value: 'Murum'},
  {label: 'Nadgaon', value: 'Nadgaon'},
  {label: 'Nagapur', value: 'Nagapur'},
  {label: 'Nala Sopara', value: 'Nala Sopara'},
  {label: 'Nalegaon', value: 'Nalegaon'},
  {label: 'Nampur', value: 'Nampur'},
  {label: 'Nandnee', value: 'Nandnee'},
  {label: 'Nandura', value: 'Nandura'},
  {label: 'Narayangaon', value: 'Narayangaon'},
  {label: 'Nardana', value: 'Nardana'},
  {label: 'Nariman Point', value: 'Nariman Point'},
  {label: 'Narkhed', value: 'Narkhed'},
  {label: 'Navapur', value: 'Navapur'},
  {label: 'Nerur', value: 'Nerur'},
  {label: 'Nevasa', value: 'Nevasa'},
  {label: 'Nighoj', value: 'Nighoj'},
  {label: 'Niphad', value: 'Niphad'},
  {label: 'Nira Narsingpur', value: 'Nira Narsingpur'},
  {label: 'Pabal', value: 'Pabal'},
  {label: 'Pahur Maharashtra', value: 'Pahur Maharashtra'},
  {label: 'Pali Raigad', value: 'Pali Raigad'},
  {label: 'Palso', value: 'Palso'},
  {label: 'Pandhurli', value: 'Pandhurli'},
  {label: 'Parel', value: 'Parel'},
  {label: 'Parner', value: 'Parner'},
  {label: 'Parseoni', value: 'Parseoni'},
  {label: 'Paturda', value: 'Paturda'},
  {label: 'Paud', value: 'Paud'},
  {label: 'Pauni', value: 'Pauni'},
  {label: 'Pedgaon', value: 'Pedgaon'},
  {label: 'Peint', value: 'Peint'},
  {label: 'Phulambri', value: 'Phulambri'},
  {label: 'Piliv', value: 'Piliv'},
  {label: 'Pimpalgaon Baswant', value: 'Pimpalgaon Baswant'},
  {label: 'Pimpalgaon Raja', value: 'Pimpalgaon Raja'},
  {label: 'Pimpri-Chinchwad', value: 'Pimpri-Chinchwad'},
  {label: 'Prabhadevi', value: 'Prabhadevi'},
  {label: 'Prakasha', value: 'Prakasha'},
  {label: 'Puntamba', value: 'Puntamba'},
  {label: 'Pural', value: 'Pural'},
  {label: 'Radhanagari', value: 'Radhanagari'},
  {label: 'Rahata', value: 'Rahata'},
  {label: 'Raireshwar', value: 'Raireshwar'},
  {label: 'Ralegaon', value: 'Ralegaon'},
  {label: 'Ramewadi', value: 'Ramewadi'},
  {label: 'Renapur', value: 'Renapur'},
  {label: 'Renavi', value: 'Renavi'},
  {label: 'Revdanda', value: 'Revdanda'},
  {label: 'Sailu', value: 'Sailu'},
  {label: 'Sakol', value: 'Sakol'},
  {label: 'Sakoli', value: 'Sakoli'},
  {label: 'Sakri', value: 'Sakri'},
  {label: 'Samudrapur', value: 'Samudrapur'},
  {label: 'Sangameshwar', value: 'Sangameshwar'},
  {label: 'Sangrampur Maharashtra', value: 'Sangrampur Maharashtra'},
  {label: 'Saoli', value: 'Saoli'},
  {label: 'Sarangkheda', value: 'Sarangkheda'},
  {label: 'Saswad', value: 'Saswad'},
  {label: 'Satpati', value: 'Satpati'},
  {label: 'Savlaj', value: 'Savlaj'},
  {label: 'Sawantvadi', value: 'Sawantvadi'},
  {label: 'Sevagram', value: 'Sevagram'},
  {label: 'Sewri', value: 'Sewri'},
  {label: 'Shedbal', value: 'Shedbal'},
  {label: 'Shevgaon', value: 'Shevgaon'},
  {label: 'Shikrapur', value: 'Shikrapur'},
  {label: 'Shirala', value: 'Shirala'},
  {label: 'Shirol', value: 'Shirol'},
  {label: 'Shirud', value: 'Shirud'},
  {label: 'Sindewahi', value: 'Sindewahi'},
  {label: 'Sindkheda', value: 'Sindkheda'},
  {label: 'Sion Mumbai', value: 'Sion Mumbai'},
  {label: 'Sironcha', value: 'Sironcha'},
  {
    label: 'Sivala East Godavari district',
    value: 'Sivala East Godavari district',
  },
  {label: 'Sonala', value: 'Sonala'},
  {label: 'Songir', value: 'Songir'},
  {label: 'Sonvad', value: 'Sonvad'},
  {label: 'Taklibhan', value: 'Taklibhan'},
  {label: 'Talbid', value: 'Talbid'},
  {label: 'Talegaon Dhamdhere', value: 'Talegaon Dhamdhere'},
  {label: 'Talode', value: 'Talode'},
  {label: 'Tardeo', value: 'Tardeo'},
  {label: 'Thalner', value: 'Thalner'},
  {label: 'Trombay', value: 'Trombay'},
  {label: 'Uruli Kanchan', value: 'Uruli Kanchan'},
  {label: 'Vadgaon', value: 'Vadgaon'},
  {label: 'Vadner', value: 'Vadner'},
  {label: 'Vairag', value: 'Vairag'},
  {label: 'Valsang', value: 'Valsang'},
  {label: 'Vangaon', value: 'Vangaon'},
  {label: 'Vashi', value: 'Vashi'},
  {label: 'Vatul', value: 'Vatul'},
  {label: 'Velas Maharashtra', value: 'Velas Maharashtra'},
  {label: 'Velneshwar', value: 'Velneshwar'},
  {label: 'Vijaydurg', value: 'Vijaydurg'},
  {label: 'Vikhroli', value: 'Vikhroli'},
  {label: 'Vile Parle', value: 'Vile Parle'},
  {label: 'Vinchur', value: 'Vinchur'},
  {label: 'Vita Maharashtra', value: 'Vita Maharashtra'},
  {label: 'Wadala', value: 'Wadala'},
  {label: 'Wadner', value: 'Wadner'},
  {label: 'Wadwani', value: 'Wadwani'},
  {label: 'Wagholi', value: 'Wagholi'},
  {label: 'Wakad', value: 'Wakad'},
  {label: 'Walgaon', value: 'Walgaon'},
  {label: 'Walki', value: 'Walki'},
  {label: 'Worli', value: 'Worli'},
];

const GJCities = [
  {label: 'Abrama', value: 'Abrama'},
  {label: 'Adalaj', value: 'Adalaj'},
  {label: 'Ahmedabad', value: 'Ahmedabad'},
  {label: 'Ahwa', value: 'Ahwa'},
  {label: 'Amod', value: 'Amod'},
  {label: 'Amreli', value: 'Amreli'},
  {label: 'Amroli', value: 'Amroli'},
  {label: 'Anand', value: 'Anand'},
  {label: 'Anjar', value: 'Anjar'},
  {label: 'Ankleshwar', value: 'Ankleshwar'},
  {label: 'Bagasra', value: 'Bagasra'},
  {label: 'Banas Kantha', value: 'Banas Kantha'},
  {label: 'Bedi', value: 'Bedi'},
  {label: 'Bhachau', value: 'Bhachau'},
  {label: 'Bharuch', value: 'Bharuch'},
  {label: 'Bhavnagar', value: 'Bhavnagar'},
  {label: 'Bhuj', value: 'Bhuj'},
  {label: 'Bhanvad', value: 'Bhanvad'},
  {label: 'Bhayavadar', value: 'Bhayavadar'},
  {label: 'Bilimora', value: 'Bilimora'},
  {label: 'Bilkha', value: 'Bilkha'},
  {label: 'Borsad', value: 'Borsad'},
  {label: 'Botad', value: 'Botad'},
  {label: 'Babra', value: 'Babra'},
  {label: 'Bantva', value: 'Bantva'},
  {label: 'Bardoli', value: 'Bardoli'},
  {label: 'Chaklasi', value: 'Chaklasi'},
  {label: 'Chalala', value: 'Chalala'},
  {label: 'Chhala', value: 'Chhala'},
  {label: 'Chhota Udepur', value: 'Chhota Udepur'},
  {label: 'Chikhli', value: 'Chikhli'},
  {label: 'Chotila', value: 'Chotila'},
  {label: 'Chanasma', value: 'Chanasma'},
  {label: 'Dabhoi', value: 'Dabhoi'},
  {label: 'Dahegam', value: 'Dahegam'},
  {label: 'Dayapar', value: 'Dayapar'},
  {label: 'Delvada', value: 'Delvada'},
  {label: 'Devbhumi Dwarka', value: 'Devbhumi Dwarka'},
  {label: 'Devgadh Bariya', value: 'Devgadh Bariya'},
  {label: 'Dhandhuka', value: 'Dhandhuka'},
  {label: 'Dhanera', value: 'Dhanera'},
  {label: 'Dharampur', value: 'Dharampur'},
  {label: 'Dhola', value: 'Dhola'},
  {label: 'Dholka', value: 'Dholka'},
  {label: 'Dhoraji', value: 'Dhoraji'},
  {label: 'Dhrol', value: 'Dhrol'},
  {label: 'Dhrangadhra', value: 'Dhrangadhra'},
  {label: 'Dhuwaran', value: 'Dhuwaran'},
  {label: 'Dhari', value: 'Dhari'},
  {label: 'Dohad', value: 'Dohad'},
  {label: 'Dungarpur', value: 'Dungarpur'},
  {label: 'Dwarka', value: 'Dwarka'},
  {label: 'Dakor', value: 'Dakor'},
  {label: 'Damnagar', value: 'Damnagar'},
  {label: 'Disa', value: 'Disa'},
  {label: 'Gadhada', value: 'Gadhada'},
  {label: 'Gandevi', value: 'Gandevi'},
  {label: 'Gandhinagar', value: 'Gandhinagar'},
  {label: 'Gariadhar', value: 'Gariadhar'},
  {label: 'Ghogha', value: 'Ghogha'},
  {label: 'Gir Somnath', value: 'Gir Somnath'},
  {label: 'Godhra', value: 'Godhra'},
  {label: 'Gondal', value: 'Gondal'},
  {label: 'Gandhidham', value: 'Gandhidham'},
  {label: 'Halvad', value: 'Halvad'},
  {label: 'Hansot', value: 'Hansot'},
  {label: 'Himatnagar', value: 'Himatnagar'},
  {label: 'Halol', value: 'Halol'},
  {label: 'Harij', value: 'Harij'},
  {label: 'Jalalpur', value: 'Jalalpur'},
  {label: 'Jambusar', value: 'Jambusar'},
  {label: 'Jamnagar', value: 'Jamnagar'},
  {label: 'Jasdan', value: 'Jasdan'},
  {label: 'Jetalsar', value: 'Jetalsar'},
  {label: 'Jetpur', value: 'Jetpur'},
  {label: 'Jhulasan', value: 'Jhulasan'},
  {label: 'Jodhpur', value: 'Jodhpur'},
  {label: 'Jodiya Bandar', value: 'Jodiya Bandar'},
  {label: 'Junagadh', value: 'Junagadh'},
  {label: 'Kachchh', value: 'Kachchh'},
  {label: 'Kadi', value: 'Kadi'},
  {label: 'Kadod', value: 'Kadod'},
  {label: 'Kapadvanj', value: 'Kapadvanj'},
  {label: 'Karamsad', value: 'Karamsad'},
  {label: 'Katpur', value: 'Katpur'},
  {label: 'Kawant', value: 'Kawant'},
  {label: 'Keshod', value: 'Keshod'},
  {label: 'Khambhat', value: 'Khambhat'},
  {label: 'Kheda', value: 'Kheda'},
  {label: 'Khedbrahma', value: 'Khedbrahma'},
  {label: 'Kheralu', value: 'Kheralu'},
  {label: 'Kodinar', value: 'Kodinar'},
  {label: 'Kosamba', value: 'Kosamba'},
  {label: 'Kundla', value: 'Kundla'},
  {label: 'Kutiyana', value: 'Kutiyana'},
  {label: 'Kalol', value: 'Kalol'},
  {label: 'Kalavad', value: 'Kalavad'},
  {label: 'Kandla', value: 'Kandla'},
  {label: 'Kanodar', value: 'Kanodar'},
  {label: 'Kathor', value: 'Kathor'},
  {label: 'Lakhtar', value: 'Lakhtar'},
  {label: 'Limbdi', value: 'Limbdi'},
  {label: 'Lalpur', value: 'Lalpur'},
  {label: 'Lathi', value: 'Lathi'},
  {label: 'Lunavada', value: 'Lunavada'},
  {label: 'Mahemdavad', value: 'Mahemdavad'},
  {label: 'Mahesana', value: 'Mahesana'},
  {label: 'Mahudha', value: 'Mahudha'},
  {label: 'Meghraj', value: 'Meghraj'},
  {label: 'Mendarda', value: 'Mendarda'},
  {label: 'Modasa', value: 'Modasa'},
  {label: 'Morbi', value: 'Morbi'},
  {label: 'Morwa', value: 'Morwa'},
  {label: 'Mundra', value: 'Mundra'},
  {label: 'Malpur', value: 'Malpur'},
  {label: 'Mandal', value: 'Mandal'},
  {label: 'Mandvi', value: 'Mandvi'},
  {label: 'Mangrol', value: 'Mangrol'},
  {label: 'Mansa', value: 'Mansa'},
  {label: 'Manavadar', value: 'Manavadar'},
  {label: 'Nadiad', value: 'Nadiad'},
  {label: 'Naliya', value: 'Naliya'},
  {label: 'Narmada', value: 'Narmada'},
  {label: 'Naroda', value: 'Naroda'},
  {label: 'Navsari', value: 'Navsari'},
  {label: 'Okha', value: 'Okha'},
  {label: 'Olpad', value: 'Olpad'},
  {label: 'Paddhari', value: 'Paddhari'},
  {label: 'Padra', value: 'Padra'},
  {label: 'Parnera', value: 'Parnera'},
  {label: 'Patan', value: 'Patan'},
  {label: 'Petlad', value: 'Petlad'},
  {label: 'Porbandar', value: 'Porbandar'},
  {label: 'Palanpur', value: 'Palanpur'},
  {label: 'Palitana', value: 'Palitana'},
  {label: 'Paliyad', value: 'Paliyad'},
  {label: 'Panch Mahals', value: 'Panch Mahals'},
  {label: 'Pardi', value: 'Pardi'},
  {label: 'Roha', value: 'Roha'},
  {label: 'Radhanpur', value: 'Radhanpur'},
  {label: 'Rajkot', value: 'Rajkot'},
  {label: 'Rajpipla', value: 'Rajpipla'},
  {label: 'Rajula', value: 'Rajula'},
  {label: 'Ranavav', value: 'Ranavav'},
  {label: 'Rapar', value: 'Rapar'},
  {label: 'Sabar Kantha', value: 'Sabar Kantha'},
  {label: 'Sachin', value: 'Sachin'},
  {label: 'Salaya', value: 'Salaya'},
  {label: 'Sankheda', value: 'Sankheda'},
  {label: 'Sarkhej', value: 'Sarkhej'},
  {label: 'Savarkundla', value: 'Savarkundla'},
  {label: 'Shivrajpur', value: 'Shivrajpur'},
  {label: 'Shahpur', value: 'Shahpur'},
  {label: 'Sihor', value: 'Sihor'},
  {label: 'Sikka', value: 'Sikka'},
  {label: 'Sinor', value: 'Sinor'},
  {label: 'Sojitra', value: 'Sojitra'},
  {label: 'Songadh', value: 'Songadh'},
  {label: 'Surendranagar', value: 'Surendranagar'},
  {label: 'Sanand', value: 'Sanand'},
  {label: 'Sayla', value: 'Sayla'},
  {label: 'Surat', value: 'Surat'},
  {label: 'Talaja', value: 'Talaja'},
  {label: 'Tankara', value: 'Tankara'},
  {label: 'Tapi', value: 'Tapi'},
  {label: 'Tharad', value: 'Tharad'},
  {label: 'The Dangs', value: 'The Dangs'},
  {label: 'Than', value: 'Than'},
  {label: 'Thasra', value: 'Thasra'},
  {label: 'Umreth', value: 'Umreth'},
  {label: 'Umrala', value: 'Umrala'},
  {label: 'Un', value: 'Un'},
  {label: 'Una', value: 'Una'},
  {label: 'Unjha', value: 'Unjha'},
  {label: 'Upleta', value: 'Upleta'},
  {label: 'Utran', value: 'Utran'},
  {label: 'Vadnagar', value: 'Vadnagar'},
  {label: 'Vadodara', value: 'Vadodara'},
  {label: 'Vallabh Vidyanagar', value: 'Vallabh Vidyanagar'},
  {label: 'Valsad', value: 'Valsad'},
  {label: 'Vapi', value: 'Vapi'},
  {label: 'Vartej', value: 'Vartej'},
  {label: 'Vasa', value: 'Vasa'},
  {label: 'Vejalpur', value: 'Vejalpur'},
  {label: 'Veraval', value: 'Veraval'},
  {label: 'Vijapur', value: 'Vijapur'},
  {label: 'Virpur', value: 'Virpur'},
  {label: 'Visnagar', value: 'Visnagar'},
  {label: 'Vyara', value: 'Vyara'},
  {label: 'Vaghodia', value: 'Vaghodia'},
  {label: 'Visavadar', value: 'Visavadar'},
  {label: 'Waghai', value: 'Waghai'},
  {label: 'Wankaner', value: 'Wankaner'},
  {label: 'Bagasara', value: 'Bagasara'},
  {label: 'Dahod', value: 'Dahod'},
  {label: 'Dangs (India)', value: 'Dangs (India)'},
  {label: 'Delwada', value: 'Delwada'},
  {label: 'Jalalpore', value: 'Jalalpore'},
  {label: 'Jodia', value: 'Jodia'},
  {label: 'Khambhalia', value: 'Khambhalia'},
  {label: 'Kutch district', value: 'Kutch district'},
  {label: 'Mandvi (Surat)', value: 'Mandvi (Surat)'},
  {label: 'Mehsana', value: 'Mehsana'},
  {label: 'Morva (Hadaf)', value: 'Morva (Hadaf)'},
  {label: 'Panchmahal district', value: 'Panchmahal district'},
  {label: 'Pavi Jetpur', value: 'Pavi Jetpur'},
  {label: 'Siddhpur', value: 'Siddhpur'},
  {label: 'Thangadh', value: 'Thangadh'},
  {label: 'Vallabhipur', value: 'Vallabhipur'},
  {label: 'Vansda', value: 'Vansda'},
  {label: 'Vaso', value: 'Vaso'},
  {label: 'Vinchhiya', value: 'Vinchhiya'},
  {label: 'Wadhai', value: 'Wadhai'},
  {label: 'Wadhwan', value: 'Wadhwan'},
  {label: 'Agol', value: 'Agol'},
  {label: 'Akrund', value: 'Akrund'},
  {label: 'Amod', value: 'Amod'},
  {label: 'Bakharla', value: 'Bakharla'},
  {label: 'Balagam', value: 'Balagam'},
  {label: 'Balasinor', value: 'Balasinor'},
  {label: 'Balisana', value: 'Balisana'},
  {label: 'Bamanbore', value: 'Bamanbore'},
  {label: 'Bandia', value: 'Bandia'},
  {label: 'Bhadran', value: 'Bhadran'},
  {label: 'Bhandu', value: 'Bhandu'},
  {label: 'Bhatha', value: 'Bhatha'},
  {label: 'Bhildi', value: 'Bhildi'},
  {label: 'Bhojpur Dharampur', value: 'Bhojpur Dharampur'},
  {label: 'Chaloda', value: 'Chaloda'},
  {label: 'Champaner', value: 'Champaner'},
  {label: 'Chuda', value: 'Chuda'},
  {label: 'Dabhoda', value: 'Dabhoda'},
  {label: 'Dandi', value: 'Dandi'},
  {label: 'Danta', value: 'Danta'},
  {label: 'Detroj', value: 'Detroj'},
  {label: 'Dhansura', value: 'Dhansura'},
  {label: 'Dharasana', value: 'Dharasana'},
  {label: 'Dhasa', value: 'Dhasa'},
  {label: 'Dholera', value: 'Dholera'},
  {label: 'Dumkhal', value: 'Dumkhal'},
  {label: 'Ghodasar', value: 'Ghodasar'},
  {label: 'Gorwa', value: 'Gorwa'},
  {label: 'Halenda', value: 'Halenda'},
  {label: 'Harsol', value: 'Harsol'},
  {label: 'Hathuran', value: 'Hathuran'},
  {label: 'Idar', value: 'Idar'},
  {label: 'Jakhau', value: 'Jakhau'},
  {label: 'Jalia', value: 'Jalia'},
  {label: 'Jambuda', value: 'Jambuda'},
  {label: 'Jarod', value: 'Jarod'},
  {label: 'Jetalpur', value: 'Jetalpur'},
  {label: 'Jetpur (Navagadh)', value: 'Jetpur (Navagadh)'},
  {label: 'Jhalod', value: 'Jhalod'},
  {label: 'Jodhpur (Ahmedabad)', value: 'Jodhpur (Ahmedabad)'},
  {label: 'Kachholi', value: 'Kachholi'},
  {label: 'Kandla port', value: 'Kandla port'},
  {label: 'Kariana', value: 'Kariana'},
  {label: 'Karjan', value: 'Karjan'},
  {label: 'Kayavarohan', value: 'Kayavarohan'},
  {label: 'Kerwada', value: 'Kerwada'},
  {label: 'Khavda', value: 'Khavda'},
  {label: 'Khedoi', value: 'Khedoi'},
  {label: 'Kherali', value: 'Kherali'},
  {label: 'Kothara', value: 'Kothara'},
  {label: 'Kotharia', value: 'Kotharia'},
  {label: 'Kukarmunda', value: 'Kukarmunda'},
  {label: 'Kukma', value: 'Kukma'},
  {label: 'Lakhpat', value: 'Lakhpat'},
  {label: 'Langhnaj', value: 'Langhnaj'},
  {label: 'Limkheda', value: 'Limkheda'},
  {label: 'Ladol', value: 'Ladol'},
  {label: 'Madhavpur Ghed', value: 'Madhavpur Ghed'},
  {label: 'Madhi', value: 'Madhi'},
  {label: 'Mahisa', value: 'Mahisa'},
  {label: 'Mahuva', value: 'Mahuva'},
  {label: 'Mahuva (Surat)', value: 'Mahuva (Surat)'},
  {label: 'Mangrol (Junagadh)', value: 'Mangrol (Junagadh)'},
  {label: 'Mithapur', value: 'Mithapur'},
  {label: 'Nadiad', value: 'Nadiad'},
  {label: 'Nagwa', value: 'Nagwa'},
  {label: 'Naldhara', value: 'Naldhara'},
  {label: 'Nargol', value: 'Nargol'},
  {label: 'Nikora', value: 'Nikora'},
  {label: 'Nizar', value: 'Nizar'},
  {label: 'Odadar', value: 'Odadar'},
  {label: 'Palanswa', value: 'Palanswa'},
  {label: 'Palsana', value: 'Palsana'},
  {label: 'Pipavav', value: 'Pipavav'},
  {label: 'Piplod', value: 'Piplod'},
  {label: 'Prabhas Patan', value: 'Prabhas Patan'},
  {label: 'Prantij', value: 'Prantij'},
  {label: 'Ranpur', value: 'Ranpur'},
  {label: 'Reha', value: 'Reha'},
  {label: 'Samakhiali', value: 'Samakhiali'},
  {label: 'Sarbhon', value: 'Sarbhon'},
  {label: 'Sardoi', value: 'Sardoi'},
  {label: 'Sathamba', value: 'Sathamba'},
  {label: 'Savli', value: 'Savli'},
  {label: 'Supedi', value: 'Supedi'},
  {label: 'Sutrapada', value: 'Sutrapada'},
  {label: 'Umarpada', value: 'Umarpada'},
  {label: 'Vadgam', value: 'Vadgam'},
  {label: 'Vaghodia INA', value: 'Vaghodia INA'},
  {label: 'Vanala', value: 'Vanala'},
  {label: 'Vanthli', value: 'Vanthli'},
  {label: 'Vasavad', value: 'Vasavad'},
  {label: 'Vataman', value: 'Vataman'},
  {label: 'Viramgam', value: 'Viramgam'},
];

const Cities = {
  Maharashtra: MHCities,
  Gujarat: GJCities,
};

export default Cities;
