export * from './MainNavigator';
export * from './AuthNavigator';
export * from './HomeNavigator';
export * from './ClientNavigator';
export * from './SoftNavigator';
export * from './LeadNavigator';
export * from './ReportNavigator';
export * from './KycNavigator';
export * from './DocNavigator';
